stages:
  - build
  - build_pypi
  - doc
  - deploy

build-LINUX:
  stage: build
  image: registry.gitlab.com/sdurobotics/docker-images/ur_rtde-build:ubuntu-1804
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - mkdir build
    - cd build
    - cmake -DPYTHON_BINDINGS:BOOL=OFF -DUSE_WERROR:BOOL=ON ..
    - make
  tags:
    - linux

build-WINDOWS:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - mkdir build
    - cd build
    - cmake -DPYTHON_BINDINGS:BOOL=OFF -DUSE_WERROR:BOOL=ON ..
    - msbuild ur_rtde.sln /property:Configuration=Release /maxcpucount:8 
  tags:
    - windows

build-MAC:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - mkdir build
    - cd build
    - cmake -DPYTHON_BINDINGS:BOOL=OFF -DUSE_WERROR:BOOL=ON ..
    - make -j3
  tags:
    - mac

build_pypi:
  stage: build_pypi
  image: registry.gitlab.com/sdurobotics/docker-images/ur_rtde-build:manylinux
  when: manual
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - ./ci/build-wheels.sh
  tags:
    - linux

sphinx_html:
  stage: doc
  image: registry.gitlab.com/sdurobotics/docker-images/ur_rtde-build:ubuntu-1804-doc
  script:
    - mkdir build
    - cd build
    - cmake -DCODE:BOOL=OFF -DDOC:STRING=html -DWERROR:BOOL=ON ..
    - make doc
  artifacts:
    paths:
      - build/doc/html
  tags:
    - linux

pages:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  only:
    refs:
      - master
  dependencies:
    - sphinx_html
  image: registry.gitlab.com/sdurobotics/docker-images/ur_rtde-build:ubuntu-1804-doc
  script:
    - mv build/doc/html public
  artifacts:
    paths:
      - public
  tags:
    - linux


    
